pantheon-systems/pantheon-advanced-page-cache

- inc/class-emitter.php
- tests/test-emitter.php
This makes pages more consistent with custom post types
> Use `single` instead of `page` for pages

- inc/class-emitter.php
- tests/class-pantheon-integrated-cdn-testcase.php
- tests/test-emitter.php
When a term is updated, then any posts it is assigned to should be
flushed. However, to prevent tons of surrogate keys on archives, we
should only emit this key on the single post view.
> Emit `term-<id>` surrogate keys for all terms assigned to a post

- .gitignore
Composer dependencies aren't relevant to the build aspect of this
project.
> Gitignore `composer.lock` and `vendor/`

- inc/class-emitter.php
- inc/class-purger.php
- tests/phpunit/test-emitter.php
- tests/phpunit/test-purger.php
Adding a key specific to author archives permits purging the author
archive without purging all posts authored by the author.
See #28
> Introduce `archive-user-<id>` surrogate key

- tests/phpunit/class-pantheon-integrated-cdn-testcase.php
- tests/phpunit/test-purger.php
Doing so exposes the fact that `clean_term_cache` is called when a post
is updated, which unexpectedly purges cache for all posts with the term
assigned.
See #28
> Persist purged keys through the entire test

- inc/class-purger.php
- pantheon-integrated-cdn.php
- tests/phpunit/class-pantheon-integrated-cdn-testcase.php
- tests/phpunit/test-purger.php
Because `wp_insert_post()` calls `clean_term_cache`, it caused an update to
Post A to purge the cache of Post B when they shared a common term. By
moving the related surrogate key purging to higher-level events, we can
mitigate unnecessary noisiness caused by `clean_*_cache`
See #28
> Only purge related surrogate keys when interpreting a higher-level event

- README.md
- inc/class-emitter.php
- inc/class-purger.php
- readme.txt
- tests/behat/home.feature
- tests/behat/page.feature
- tests/behat/post.feature
- tests/phpunit/test-emitter.php
- tests/phpunit/test-purger.php
This is a more precise naming strategy.
Also drops `user-<id>` from index views, which is unnecessarily noisy.
See #28
> Deprecate `archive-*` surrogate key in favor of `post-*`

- pantheon-advanced-page-cache.php
- tests/phpunit/bootstrap.php
- tests/phpunit/pantheon-edge-functions.php
- tests/phpunit/test-functions.php
While Exceptions are perfectly fine in PHPlandia, WordPress doesn't know
how to handle them. Instead, let's catch them and return `WP_Error`
objects instead.
Fixes #45
> Catch Exceptions thrown by `pantheon_clear_edge_*()` functions

- inc/class-purger.php
- pantheon-advanced-page-cache.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-purger.php
Only pay attention to the `wp_insert_post` action when the post is
published. Hook into `transition_post_status` for drafts going to
publish or vice versa.
> Ensure updates to post drafts don't flush the homepage cache

- README.md
- inc/class-emitter.php
- readme.txt
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter.php
This is more precise, and creates space for a second method specific to
REST API requests.
See #8
> Rename `Emitter::get_surrogate_keys()` to `Emitter::get_main_query_surrogate_keys()`

- circle.yml
Upstream tests are failing now, so we should just ignore for the time
being
> Disable Circle builds

- inc/class-emitter.php
- inc/class-purger.php
- tests/phpunit/test-emitter-rest-api.php
- tests/phpunit/test-purger.php
Doing so gives us a greater degree of precision when triggering purges.
See #8
> Prefix REST API surrogate keys with `rest-`

- inc/class-emitter.php
- inc/class-purger.php
- pantheon-advanced-page-cache.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter-rest-api.php
- tests/phpunit/test-purger.php
> Emit surrogate keys for `/wp/v2/settings`; purge on `updated_option`

- inc/class-emitter.php
- inc/class-purger.php
- pantheon-advanced-page-cache.php
- tests/phpunit/bootstrap.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter-rest-api.php
- tests/phpunit/test-purger.php
When a post is updated, we don't know how its new values will affect the
collections it's represented in. As such, we need to purge all possible
collections, instead of the collections it was previously present in.
Behavior only affects updates to published posts, because the assumption
is that unpublished posts won't ever be cached.
See #8
> Purge post collection endpoints more liberally

- inc/class-emitter.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter-rest-api.php
> Emit surrogate keys for `/wp/v2/comments` endpoints

- inc/class-emitter.php
- inc/class-purger.php
- pantheon-advanced-page-cache.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter-rest-api.php
- tests/phpunit/test-purger.php
Because a post's visibility affects a comment's visibility, we need to
purge comment endpoints when the post's visibility changes.
See #8
> Purge comment endpoints when a post is updated

- inc/class-user-interface.php
- tests/phpunit/test-emitter-rest-api.php
Doing so lets both editors and admins flush the cache.
Previously https://github.com/pantheon-systems/WordPress/pull/71
> Permit flush URL cache if `delete_others_posts` or `manage_options`

- inc/class-emitter.php
See https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/88#issuecomment-303839274
> Disable emitting surrogate keys for the admin, unless added by filter

- inc/class-emitter.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter-rest-api.php
> Ensure use of `?_embed` emits correct surrogate keys

- inc/class-purger.php
- pantheon-advanced-page-cache.php
Having filter hooks allows for a cleaner extension.
> Filter hooks for surrogate key for purging

- bin/behat-prepare.sh
- composer.lock
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 21 updates, 0 removals
- Updating symfony/polyfill-php80 (v1.17.0 => v1.17.1): Loading from cache
- Updating symfony/event-dispatcher (v5.1.0 => v5.1.2): Loading from cache
- Updating symfony/polyfill-ctype (v1.17.0 => v1.17.1): Loading from cache
- Updating symfony/yaml (v5.1.0 => v5.1.2): Loading from cache
- Updating symfony/filesystem (v5.1.0 => v5.1.2): Loading from cache
- Updating symfony/config (v4.4.9 => v4.4.10): Loading from cache
- Updating symfony/dependency-injection (v4.4.9 => v4.4.10): Loading from cache
- Updating symfony/polyfill-mbstring (v1.17.0 => v1.17.1): Loading from cache
- Updating symfony/polyfill-intl-normalizer (v1.17.0 => …
```
> Update Composer dependencies (2020-06-03)

- README.md
- readme.txt
See https://wordpress.org/support/topic/minor-typo-in-documentation/
> Add more text to fix parsing issue on WordPress.org

- .github/workflows/lint.yml
- README.md
Ensures the header section of README.md handles newlines correctly in rendered markdown.
See https://github.com/pantheon-systems/validate-readme-spacing
> Lint README for lost spacing

- README.md
- inc/class-emitter.php
- readme.txt
- tests/phpunit/test-emitter.php
- add new filter `pantheon_should_add_terms`
- `$wp_query->is_singular() || $wp_query->is_page()` is redundant
> [BUGS-3964] Add filter to skips surrogate keys for taxonomy terms

- README.md
- package-lock.json
- package.json
- pantheon-advanced-page-cache.php
- readme.txt
Intended to bump this as part of #239, but forgot to make the change. As 239 is a new feature, this is now a minor release, not a patch.
As part of updating package-lock, npm also updated the format.
> [BUGS-3964] Bump dev version to 1.4.0 && update lockfileVersion

- readme.txt
Fixes the broken code block for the `pantheon_should_add_terms` filter documentation.
> [CMSP-574] Fix broken code syntax

- CONTRIBUTING.md
- README.md
- readme.txt
- tests/phpunit/test-emitter-rest-api.php
This closes the loop on #217 #237 because we didn't actually have any tests validating the REST (or GraphQL) responses and that they contain the Surrogate Key headers. This PR adds two new tests in `test-emitter-rest-api.php` -- one that tests the REST APi headers to ensure that they contain the expected surrogate keys, and the other to test the GraphQL response for the same. While the `test_graphql_response_headers` test doesn't _really_ make a lot of sense inside the `*rest-api.php` test case, given it's the only test of its kind, I opted to keep it in the existing "API stuff" test suite rather than starting a new one, particularly since the REST API tests were already broken out of `test-emitter.php`. If/when we have more GraphQL-specific tests, we can create a …
> [BUGS-5914] Add PHP unit test cases for GraphQL and REST API response headers
