pantheon-systems/pantheon-advanced-page-cache

- .travis.yml
- inc/class-emitter.php
- inc/class-purger.php
- phpcs.ruleset.xml
- tests/class-pantheon-integrated-cdn-testcase.php
> Run WPCS against every Travis build

- .travis.yml
> Remove unnecessary WP 4.6.1 builds

- tests/class-pantheon-integrated-cdn-testcase.php
- tests/test-emitter.php
> Add explicit tests for date archives

- inc/class-emitter.php
> Emit header as `Surrogate-Key`, not `Surrogate-Keys`

- behat.yml
- bin/behat-prepare.sh
- tests/behat/home.feature
- tests/behat/page.feature
- tests/behat/post.feature
> Add a few basic tests for asserting emitted tags

- inc/class-emitter.php
- inc/class-purger.php
- pantheon-integrated-cdn.php
- phpcs.ruleset.xml
- tests/phpunit/class-pantheon-integrated-cdn-testcase.php
- tests/phpunit/test-emitter.php
- tests/phpunit/test-purger.php
> Add PHPDoc throughout

- .gitignore
- composer.lock
Doing so ensures we get a consistent version of our dependencies
> Commit the `composer.lock` file

- tests/phpunit/class-pantheon-integrated-cdn-testcase.php
- tests/phpunit/test-purger.php
> Assert purged URIs for more clarity into purge events -> affected URIs

- inc/class-admin.php
- pantheon-integrated-cdn.php
> Hook an explanation about Advanced Page Cache to bottom of settings page

- tests/phpunit/class-pantheon-integrated-cdn-testcase.php
- tests/phpunit/test-emitter.php
- tests/phpunit/test-purger.php
> Add a suite of tests for custom post types and taxonomies

- inc/class-purger.php
- pantheon-integrated-cdn.php
- tests/phpunit/class-pantheon-integrated-cdn-testcase.php
> Include dedicated `pantheon_wp_clear_edge_*()` functions for devs to use

- inc/class-purger.php
- tests/phpunit/test-purger.php
> Explicitly purge archives of terms assigned to a post

- inc/class-emitter.php
> Add a filter for the surrogate keys to be emitted

- README.md
- readme.txt
> Update documentation of emitted surrogate keys

- README.md
- readme.txt
> Add further documentation on reusable APIs

- inc/class-admin.php
From https://github.com/pantheon-systems/pantheon-integrated-cdn/pull/30#pullrequestreview-7733504
> Fix settings page title

- circle.yml
> Circle build should run against `pantheon-advanced-page-cache`

- README.md
- inc/class-cli.php
- pantheon-advanced-page-cache.php
- phpcs.ruleset.xml
- readme.txt
> Add a few commands for managing the page cache

- inc/class-user-interface.php
- pantheon-advanced-page-cache.php
> Register a toolbar button to clear cache for current page

- inc/class-user-interface.php
- pantheon-advanced-page-cache.php
See https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/49#issuecomment-259847442
> Rename "Clear Page Cache" to "Clear URL Cache"

- .distignore
- .travis.yml
- inc/class-emitter.php
- multisite.xml.dist
- pantheon-advanced-page-cache.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-emitter-rest-api.php
- tests/phpunit/test-purger.php
> Add assertions for affected REST API endpoints in purge events

- inc/class-emitter.php
- inc/class-purger.php
- pantheon-advanced-page-cache.php
- tests/phpunit/test-emitter-rest-api.php
- tests/phpunit/test-purger.php
> Emit keys for REST API collection endpoints; purge for new resource

- README.md
- readme.txt
> Documented emitted and purged surrogate keys for the REST API

- README.md
- pantheon-advanced-page-cache.php
- readme.txt
> Update README for v0.1.0

- inc/class-user-interface.php
- pantheon-advanced-page-cache.php
See https://github.com/pantheon-systems/WordPress/issues/84#issuecomment-263698609
See #70
> Drop settings UI in plugin in favor of upstream

- bin/behat-cleanup.sh
- bin/behat-prepare.sh
- bin/behat-test.sh
- circle.yml
Cribbed from https://github.com/pantheon-systems/wp-redis/pull/167
See #59
> Use Terminus 1.0 in Circle tests

- inc/class-emitter.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-purger.php
> Prevent error notices by only accessing `$rest_base` property when set

- inc/class-emitter.php
- inc/class-purger.php
- tests/phpunit/class-pantheon-advanced-page-cache-testcase.php
- tests/phpunit/test-purger.php
Added functionality to purge RSS feeds on content status changes
> Added surrogate support for feeds

- README.md
- readme.txt
> Add README example of pre-rendering data

- README.md
- readme.txt
See https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/119
> Adding debugging header to README.md

- .travis.yml
- README.md
- bin/behat-prepare.sh
- composer.json
- phpunit.xml.dist
- readme.txt
* Switches PHPCS and PHPUnit to Composer dependencies.
* Adds PHP 7.3 to Travis build matrix (fixes #131)
* Removes < PHP 7.1 from Travis build matrix
* Updates Behat tests for WP 5.0
> Various maintenance updates to test suite

- .circleci/config.yml
> Update CircleCI config file to use nightly build + Pantheon CI tools

- tests/behat/rest-api.feature
> Add some basic tests for REST API behavior

- .travis.yml
- composer.lock
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 35 updates, 2 removals
- Removing symfony/contracts (v1.1.0)
- Removing symfony/class-loader (v3.4.27)
- Updating symfony/polyfill-ctype (v1.11.0 => v1.14.0): Loading from cache
- Updating symfony/yaml (v4.2.8 => v5.0.5): Downloading (100%)
- Updating symfony/polyfill-mbstring (v1.11.0 => v1.14.0): Loading from cache
- Installing symfony/translation-contracts (v2.0.1): Loading from cache
- Updating symfony/translation (v4.2.8 => v4.4.5): Downloading (100%)
- Installing psr/event-dispatcher (1.0.0): Downloading (100%)
- Installing symfony/event-dispatcher-contracts (v2.0.1): Downloading (100%)
- Updating symfony/event-dispatcher (v4.2.8 => v5.0.5): …
```
> Update Composer dependencies to latest (2020-03-02)

- .circleci/config.yml
- composer.lock
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 11 updates, 0 removals
- Updating symfony/event-dispatcher (v5.1.2 => v5.1.3): Loading from cache
- Updating symfony/yaml (v5.1.2 => v5.1.3): Loading from cache
- Updating symfony/filesystem (v5.1.2 => v5.1.3): Loading from cache
- Updating symfony/config (v4.4.10 => v4.4.11): Loading from cache
- Updating symfony/dependency-injection (v4.4.10 => v4.4.11): Loading from cache
- Updating symfony/string (v5.1.2 => v5.1.3): Loading from cache
- Updating symfony/console (v5.1.2 => v5.1.3): Loading from cache
- Updating symfony/translation (v4.4.10 => v4.4.11): Loading from cache
- Updating symfony/css-selector (v5.1.2 => v5.1.3): Loading from cache
- Updating …
```
> Update Composer dependencies (2020-08-03)
